-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

-- CREATE DATABASE locadora


CREATE TABLE IF NOT EXISTS public.filmes
(
    id serial NOT NULL,
    id_genero integer NOT NULL,
    valor double precision NOT NULL,
    titulo character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.generos
(
    id serial NOT NULL,
    genero character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dvds
(
    id serial NOT NULL,
    id_filme integer NOT NULL,
    quantidade integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.atores
(
    id serial NOT NULL,
    nome character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.atores_filme
(
    id serial NOT NULL,
    id_filme integer NOT NULL,
    id_ator integer NOT NULL,
    personagem character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.clientes
(
    id serial NOT NULL,
    nome character varying NOT NULL,
    sobrenome character varying NOT NULL,
    telefone character varying NOT NULL,
    endereco character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.emprestimos
(
    id serial NOT NULL,
    id_cliente integer NOT NULL,
    data date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.filmes_emprestimo
(
    id serial NOT NULL,
    id_emprestimo integer NOT NULL,
    id_dvd integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.devolucoes
(
    id serial NOT NULL,
    id_emprestimo integer NOT NULL,
    data date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.filmes_devolucao
(
    id serial NOT NULL,
    id_filme_emprestimo integer NOT NULL,
    id_devolucao integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.filmes
    ADD CONSTRAINT fk_filmes_1 FOREIGN KEY (id_genero)
    REFERENCES public.generos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dvds
    ADD CONSTRAINT fk_dvds_1 FOREIGN KEY (id_filme)
    REFERENCES public.filmes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.atores_filme
    ADD CONSTRAINT fk_atores_filme_1 FOREIGN KEY (id_filme)
    REFERENCES public.filmes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.atores_filme
    ADD CONSTRAINT fk_atores_filme_2 FOREIGN KEY (id_ator)
    REFERENCES public.atores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.emprestimos
    ADD CONSTRAINT fk_emprestimos_1 FOREIGN KEY (id_cliente)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.filmes_emprestimo
    ADD CONSTRAINT fk_filmes_emprestimo_1 FOREIGN KEY (id_emprestimo)
    REFERENCES public.emprestimos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.filmes_emprestimo
    ADD CONSTRAINT fk_filmes_emprestimo_2 FOREIGN KEY (id_dvd)
    REFERENCES public.dvds (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.devolucoes
    ADD CONSTRAINT fk_devolucoes_1 FOREIGN KEY (id_emprestimo)
    REFERENCES public.emprestimos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.filmes_devolucao
    ADD CONSTRAINT fk_filmes_devolucao_1 FOREIGN KEY (id_filme_emprestimo)
    REFERENCES public.filmes_emprestimo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.filmes_devolucao
    ADD CONSTRAINT fk_filmes_devolucao_2 FOREIGN KEY (id_devolucao)
    REFERENCES public.devolucoes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;